# Generated by Django 5.2.7 on 2026-02-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_index=True, max_length=50)),
                ('search_query', models.CharField(max_length=500)),
                ('urls_discovered', models.JSONField(default=list)),
                ('courses_created', models.IntegerField(default=0)),
                ('courses_skipped', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
